from n_gram import Predictor

p = 'model/t8-2s-e10-v05-lr05d-mc100-ss5-nwout-adg-win10'
q = 'model/wiki1'
q2 = 'model/wiki2'

pred = Predictor(q2)
#w2gm.visualize_embeddings()

a = 'hypr is a provider of real time analytics solution allowing brand owners to partner with social media influencers to promote their brands the platform provides influencer audience demographic psychographic and geographic data the company was founded in and is based in new york united states it has office in tel aviv israel hypr is an influencer marketing platform the farm provides clients audience demographics of social influencers it allows marketers to engage their target audience by hiring any number of influencers ranging from a single to thousands the platform allows automation in influencer discovery by narrowing down large number of options to relevant ones the company tracks over million influencers and billion social accounts daily the company was founded in gil eyal who is the current ceo of the company eyal is a known figure in the israeli startup scene he has a history of working with celebrities as the coo of photo sharing app mobli where he became a pioneer in the influencer marketing space for the app he recruited celebrities including leonardo dicaprio serena williams lil wayne and austin mahone the company claims to have a different algorithm from other marketing platform the engine of the platform crawls different social media accounts around the world and uses proprietary databases and algorithms to understand the nature of their audience demographics allowing the engine to make informed recommendation and find influencers that directly reach to the relevant audience in june hypr audience demographic and profile information as its feature the engine uses an index of million influencers across major social channels its client base includes fortune brands and pr and advertising agencies globally including lvmh hearst magazines calvin klein time inc and est e lauder'
b = 'wanghan died was a chinese historical geographer and a disciple of the late qing dynasty scholar yang shoujing he is known for completing the shui jing zhu shu a monumental annotation of the th century geographic classic shui jing zhu wanghan was born in zhijiang county hubei province and studied under the prominent historical geographer and bibliophile yang shoujing who was also a native of hubei yang spent most of his life annotating the th century geographic work shui jing zhu having completed volumes of annotation he died in without completing the work xiong carried on the project and wrote another volumes he also made the final editing of the entire work painstakingly proofreading the annotations word by word it took xiong years to complete the work known as the shui jing zhu shu he refused offers made by japanese scholars to purchase the book however when he learned that the descendants of yang shoujing had secretly sold some manuscripts he committed suicide by hanging himself in the second sino japanese war soon broke out in the chinese government paid great attention to the protection of the manuscript as well as yang shoujing s precious book collection scholar fu sinian negotiated on behalf of the academia sinica and the ministry of education to purchase the manuscript from yang s heir yang mianzhi for dollars and brought it to hong kong for safekeeping it was eventually published in taiwan the early s and in mainland china in the influential historian gu jiegang commented that the shui jing zhu shu brought to a point of culmination the textual research of the classic of waterways of the previous three centuries he greatly admired yang shoujing and wanghan for their single minded devotion to the task and xiong s devotion to his master '

# t = pred.get_neightbours('hypr', a)
# for i in t:
#     print(i, pred.model.get_dist(i))

print(pred.get_similar_words('wanghan', b))
#print(pred.model.find_nearest_dist(1111,0))
